steps:

- id: "Executando teste"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src/sum']

- id: "Criando a imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-education-desafio-ci:latest', '.']

images:
- 'gcr.io/$PROJECT_ID/code-education-desafio-ci:latest'